### PR TITLE
Plugin cleaning and deploy

### PR DESCRIPTION
**Pull request by ahgittin**
- brooklyn-tomcat tosca can be added manually correctly (in addition to the auto-import)
- attempt deployments using rest api
- pseudo-track deployments to brooklyn in case plugin isn't working

### CODE REVIEW

**Comment by ahgittin** [comment]
Happy to hear if you have any comments on my use of Alien API here @lucboutier

**Comment by lucboutier** [comment]
I think that's quite a good usage, probably it would be better to use the PaaSTopology object witch is a pre-processed version of the Topology where we do map the hosted_on relationships as children(s) etc. But for now as we don't support relationships really this is not that much a big deal.

**Comment by lucboutier** [comment]
I think also as we right now only support the mapping of Brooklyn nodes it would be indeed a good catch to add a brooklyn.nodes.Root node in the catalog and make all Brooklyn nodes inherit so we can add some kind of unsupported exceptions/warnings in the camp generation process.

**Comment by ahgittin** [comment]
Great feedback.  Thanks.  /cc @robertgmoss

**Pull request merged**
